---
- name: Add User to Cisco Nexus Switch
  hosts: switchs
  gather_facts: no
  connection: network_cli
  tasks:
    - name: configure the exec banner
      cisco.nxos.nxos_banner:
        banner: exec
      text: |
        this is my exec banner
        that contains a multiline
        string
        state: present

