- name: "Connection au devices"
  hosts: switchs
  gather_facts: no
  become: yes

  tasks:
   - name: Creation d'un utilisateur
     cisco.nxos.nxos_user:
       name: netops1
       configured_password: "netops2023"
       update_password: always
       state: present
          
        
