---
- name: Add User to Cisco Nexus Switch
  hosts: switchs
  gather_facts: no
  connection: network_cli
  tasks:
    - name: create a new user
      cisco.nxos.nxos_user:
        name: ansible
        sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present

