---
- name: Configure NTP on Cisco Routers
  hosts: routers
  gather_facts: no
  become: yes
  tasks:
    - name: Configure NTP servers
      ios_config:
        lines:
          - ntp server {{ ntp_server }} prefer
        parents: ntp
      vars:
        ntp_server: 1.2.3.4  # Replace with your NTP server's IP address

    - name: Save configuration
      ios_command:
        commands:
          - write memory
