---
- name: Backup Cisco Router Configuration
  hosts: routers
  gather_facts: true

  tasks:
    - name: Gather facts from Cisco IOS devices
      ios_facts:

    - name: Backup Cisco Router Configuration
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}-{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}.cfg"
          overwrite: true
      register: backup_result

    - name: Print backup result
      debug:
        var: backup_result
