---
- name: Backup Cisco Router Configuration
  hosts: cisco_routers
  gather_facts: true
  tasks:
    - name: Run show running-config command
      ios_command:
        commands:
          - show running-config
      register: show_output

    - name: Save running-config to file
      copy:
        content: "{{ show_output.stdout[0] }}"
        dest: "/path/to/save/{{ inventory_hostname }}-backup.cfg"
