---
- name: Backup Cisco Router Configuration
  hosts: routers
  gather_facts: true
  tasks:
    - name: backup configuration of all devices
        cisco.ios.ios_config:
          backup: yes
      register: output_config

   - name: Rename backup files
       copy:
         src: "{{ output_config.backup_path}}"
         dest: "./backup{{inventory_hostname}}.cfg"
