---
- name: Configure NTP on Cisco Routers
  hosts: routers
  gather_facts: no
  tasks:
    - name: Configure NTP servers
      ios_config:
        lines:
          - ntp server 0.pool.ntp.org
          - ntp server 1.pool.ntp.org
        parent: global
