- name: "Demonstrate connecting to switches"
  hosts: routers
  gather_facts: no
  become: yes

  tasks:
   - name: Add a user specifying password type
     cisco.ios.ios_user:
        name: ansibletest4
        configured_password: "{{ new_password }}"
        password_type: password
          
        
