- name: configuration interfaces Gigaethernet 0/0 et gigaethernet 0/1 au niveau de router R2
  hosts: R2
  gather_facts: no
  connection: network_cli
  become: yes
  pre_tasks:
    - name: configure interface for spine pour R2
      ios_config:
        lines:
        - interface g0/0
        - ip address 30.0.0.2 255.255.255.0
        - no shutdown
        save_when: modified

    - name: configure interface spine pour  R2
      ios_config:
        lines:
        - interface g0/1
        - ip address 40.0.0.2 255.255.255.0
        - description "spine"
        - no shutdown
        save_when: modified
