- name: "Demonstrate connecting to routers"
  hosts: routers
  gather_facts: no
  become: yes

  tasks:
   - name: Changer mot de passe utilisateur
     cisco.ios.ios_user:
       name: ansibletest5
       configured_password: "issam1988"
       update_password: always
       state: present
          
        
