---
- name: "Connection au devices"
  hosts: routers
  gather_facts: no
  become: yes

  tasks:
    - name: accorder role a l'utilisateur
      cisco.ios.ios_user:
        aggregate:
          -name: ansibletest1
        privilege: 15
        state: present  
