---
- name: Apply Startup Configuration to Cisco Devices
  hosts: routers
  gather_facts: no
  tasks:
    - name: Copy startup configuration to device
      ios_config:
        lines:
          - "{{ lookup('file', '/path/to/your/startup_config.txt') }}"
      register: config_result

    - name: Save the result to a log file
      copy:
        content: "{{ config_result.stdout_lines | join('\n') }}"
        dest: "/tmp/config_result_{{ inventory_hostname }}.txt"
