---
- name: Afficher les utilisateurs sur un périphérique Cisco IOS
  hosts: routers
  gather_facts: no
  become: yes
  tasks:
    - name: Exécuter la commande "show users"
      ios_command:
        commands:
          - show users
      register: result

    - name: les utilisateurs sont 
      debug:
        var: result.stdout_lines
