---
- name: "Connection au devices"
  hosts: routers
  gather_facts: no
  become: yes

  tasks:
    - name: Delete users with aggregate
      cisco.ios.ios_user:
        aggregate:
          - name: ansibletest1
          - name: ansibletest5
          - name: ansibletest4
        state: absent
