---
- name: "Connection au devices"
  hosts: routers
  gather_facts: no
  become: yes

  tasks:
    - name: Suppression utilisateurs .
      cisco.ios.ios_user:
        aggregate:
          - name: ansibletest1
          - name: ansibletest5
          - name: netops1
        state: absent
