- name: Create vlan
  hosts: switchs
  become: yes
  ios_vlan:
    vlan_id: 100
    name: test-vlan
    state: present

- name: Add interfaces to VLAN
  ios_vlan:
    vlan_id: 100
    interfaces:
      - Ethernet1/11
      - Ethernet1/12

- name: Check if interfaces is assigned to VLAN
  ios_vlan:
    vlan_id: 100
    associated_interfaces:
      - Ethernet1/11
      - Ethernet1/12